import type { Transaction, Category, Debt, Event } from '@/types';
import {
  ArrowDown,
  ArrowUp,
  Briefcase,
  Car,
  Cat,
  Dumbbell,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Pizza,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  Ticket,
} from 'lucide-react';

export const transactions: Transaction[] = [
  {
    id: '1',
    type: 'income',
    amount: 5000,
    currency: 'USD',
    date: '2024-07-01',
    wallet: 'Main Bank Account',
    category: 'Salary',
    description: 'Monthly Salary',
  },
  {
    id: '2',
    type: 'expense',
    amount: 75.5,
    currency: 'USD',
    date: '2024-07-02',
    wallet: 'Credit Card',
    category: 'Food',
    description: 'Grocery shopping at Whole Foods',
    event: 'Weekly Groceries',
  },
  {
    id: '3',
    type: 'expense',
    amount: 1200,
    currency: 'USD',
    date: '2024-07-01',
    wallet: 'Main Bank Account',
    category: 'Housing',
    description: 'Rent Payment',
  },
  {
    id: '4',
    type: 'expense',
    amount: 45.0,
    currency: 'USD',
    date: '2024-07-03',
    wallet: 'Credit Card',
    category: 'Transport',
    description: 'Gasoline for car',
  },
  {
    id: '5',
    type: 'expense',
    amount: 30.0,
    currency: 'USD',
    date: '2024-07-05',
    wallet: 'Debit Card',
    category: 'Entertainment',
    description: 'Movie tickets for two',
  },
  {
    id: '6',
    type: 'income',
    amount: 250,
    currency: 'USD',
    date: '2024-07-06',
    wallet: 'PayPal',
    category: 'Freelance',
    description: 'Freelance graphic design work',
  },
  {
    id: '7',
    type: 'expense',
    amount: 25.2,
    currency: 'USD',
    date: '2024-06-15',
    wallet: 'Credit Card',
    category: 'Food',
    description: 'Dinner with friends',
  },
  {
    id: '8',
    type: 'expense',
    amount: 120.0,
    currency: 'USD',
    date: '2024-06-20',
    wallet: 'Credit Card',
    category: 'Shopping',
    description: 'New shoes',
  },
];

export const categories: Category[] = [
  // Income
  { id: 'cat-inc-1', name: 'Salary', type: 'income', icon: Briefcase },
  { id: 'cat-inc-2', name: 'Freelance', type: 'income', icon: ArrowUp },
  { id: 'cat-inc-3', name: 'Gifts', type: 'income', icon: Gift },
  { id: 'cat-inc-4', name: 'Investments', type: 'income', icon: ArrowUp },

  // Expense
  { id: 'cat-exp-1', name: 'Food', type: 'expense', icon: Pizza },
  { id: 'cat-exp-2', name: 'Housing', type: 'expense', icon: Home },
  { id: 'cat-exp-3', name: 'Transport', type: 'expense', icon: Car },
  { id: 'cat-exp-4', name: 'Entertainment', type: 'expense', icon: Ticket },
  { id: 'cat-exp-5', name: 'Shopping', type: 'expense', icon: ShoppingBag },
  { id: 'cat-exp-6', name: 'Health', type: 'expense', icon: HeartPulse },
  { id: 'cat-exp-7', name: 'Education', type: 'expense', icon: GraduationCap },
  { id: 'cat-exp-8', name: 'Travel', type: 'expense', icon: Plane },
  { id: 'cat-exp-9', name: 'Utilities', type: 'expense', icon: Receipt },
  { id: 'cat-exp-10', name: 'Pets', type: 'expense', icon: Cat },
  { id: 'cat-exp-11', name: 'Fitness', type: 'expense', icon: Dumbbell },
  { id: 'cat-exp-12', name: 'Clothing', type: 'expense', icon: Shirt },
];

export const debts: Debt[] = [
  {
    id: 'debt-1',
    type: 'payable',
    person: 'John Doe',
    amount: 150,
    dueDate: '2024-08-01',
    status: 'unpaid',
    paidAmount: 0,
  },
  {
    id: 'debt-2',
    type: 'receivable',
    person: 'Jane Smith',
    amount: 200,
    dueDate: '2024-07-25',
    status: 'partial',
    paidAmount: 100,
  },
  {
    id: 'debt-3',
    type: 'receivable',
    person: 'Mike Johnson',
    amount: 50,
    dueDate: '2024-06-30',
    status: 'paid',
    paidAmount: 50,
  },
];

export const events: Event[] = [
  {
    id: 'event-1',
    name: 'Summer Vacation to Italy',
    date: '2024-08-10',
    description: 'A 10-day trip exploring Rome, Florence, and Venice.',
  },
  {
    id: 'event-2',
    name: 'Friend\'s Wedding',
    date: '2024-09-05',
    description: 'Attending and celebrating the wedding of a close friend.',
  },
];
